config/routes.rb
Tribute::Application.routes.draw do
  resources :pages, :except => [:show, :update, :destroy]

  devise_for :users,
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks"
    },
    path: "",
    path_names: {
      sign_up: "signup",
      sign_in: "login",
      sign_out: "logout"
    }

  namespace :admin do
    root :to => 'home#index'
    resources :templates
  end

  root :to => 'home#index'

  get ":id", to: 'pages#show', as: "page"
  put ":id", to: 'pages#update', as: "page"
  delete ":id", to: 'pages#destroy', as: "page"
end

app/models/identities/facebook.rb
class Identities::Facebook < Identity
  def contacts
    fb_graph.friends
  end

  def first_name
    omniauth_info[:first_name]
  end

  def email
    omniauth_info[:email]
  end

  def username
    omniauth_info[:nickname]
  end

  def image
    "http://graph.facebook.com/#{uid}/picture?type=large"
  end

  def last_name
    omniauth_info[:last_name]
  end

  private
  def fb_graph
    @fb_graph ||= FbGraph::User.fetch(uid, access_token: omniauth_credentials[:token])
  end
end

app/models/identities/twitter.rb
class Identities::Twitter < Identity
  CONFIG = YAML::load_file("#{Rails.root}/config/omniauth/twitter.yml")[Rails.env]

  def contacts
    @contacts ||= twitter_client.friends.all
  end

  # first name is all characters before the rightmost space
  # e.g. Jesus H. Christ -> Jesus H.
  def first_name
    omniauth_info[:name].slice(/.*?(?=\s?[^ ]+$)/)
  end

  # last name is all characters after the rightmost space
  # e.g. Jesus H. Christ -> Christ
  def last_name
    omniauth_info[:name].slice(/[^ ]+$/)
  end

  def email
    ""
  end

  # Twitter only returns a smaller image; this is the full size
  def image
    omniauth_info[:image].sub(/_normal(?=\.\w{3}$)/, '')
  end

  private
  def twitter_client
    @twitter_client ||= Twitter::Client.new({
      consumer_key:       CONFIG["key"],
      consumer_secret:    CONFIG["secret"],
      oauth_token:        omniauth_credentials[:token],
      oauth_token_secret: omniauth_credentials[:secret]
    })
  end
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  serialize :omniauth_credentials
  serialize :omniauth_extra
  serialize :omniauth_info

  scope :for_provider, lambda { |provider| where(provider: provider) }

  def self.find_or_create_by_omniauth_hash(auth_hash)
    where(provider: auth_hash[:provider], uid: auth_hash[:uid]).first_or_create do |identity|
      [:credentials, :extra, :info].each do |sym|
        identity.send(:"omniauth_#{sym}=", auth_hash[sym])
      end
    end
  end

  def provider=(provider)
    super

    self.type = self.class.type_from_provider(provider)
  end

  def first_name
    info[:first_name]
  end

  def last_name
    info[:last_name]
  end

  def image
  end

  def url
    info[:urls][:"#{provider.capitalize}"]
  end

  private
  def self.type_from_provider(provider)
    # make this simple until we might need a case statement
    "#{self.to_s.pluralize}::#{provider.camelize}"
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId

  attr_accessible :description, :main_image, :name, :tagline, :template_id,
                  :main_image_cache

  belongs_to :owner, class_name: "User"
  belongs_to :template

  validates :template_id, presence: true
  validates :name, presence: true

  friendly_id :name, use: :slugged

  mount_uploader :main_image, PhotoUploader

  def allows_editor?(user)
    return false if user.nil?
    return user.admin? || self.owner == user
  end
end

app/models/template.rb
class Template < ActiveRecord::Base
  attr_accessible :class_name, :created_by_id, :description, :name

  belongs_to :created_by, class_name: "User"
  has_many :pages

  validates :name, :presence => true
  validates :class_name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  has_many :identities, dependent: :destroy
  has_many :pages, foreign_key: :owner_id

  attr_accessible :email, :password, :password_confirmation, :remember_me

  validates :first_name, :presence => true

  friendly_id :full_name, use: :slugged

  def self.find_or_create_by_omniauth_hash(auth_hash, current_user = nil)
    identity = Identity.find_or_create_by_omniauth_hash(auth_hash)
    identity = identity.becomes(identity.type.constantize)

    user ||= identity.user || User.new

    user.first_name      ||= identity.first_name
    user.last_name       ||= identity.last_name
    user.email = identity.email if user.email.blank?
    user.profile_picture ||= identity.image
    user.save

    user.identities << identity

    user
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    before_filter :requires_admin

    protected
      def requires_admin
        unless user_signed_in? && current_user.admin?
          render template: "errors/unauthorized", layout: "application", status: 401 and return false
        end
      end
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < AdminController
    def index
    end
  end
end

app/controllers/admin/templates_controller.rb
module Admin
  class TemplatesController < AdminController
    def index
      @templates = Template.all
    end

    def show
      @template = Template.find(params[:id])
    end

    def new
      @template = Template.new
    end

    def edit
      @template = Template.find(params[:id])
    end

    def create
      @template = Template.new(params[:template])
      @template.created_by = current_user

      if @template.save
        redirect_to [:admin, @template], notice: 'Template was successfully created.'
      else
        render :new
      end
    end

    def update
      @template = Template.find(params[:id])

      if @template.update_attributes(params[:template])
        redirect_to [:admin, @template], notice: 'Template was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @template = Template.find(params[:id])
      @template.destroy

      redirect_to admin_templates_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from ActiveRecord::RecordNotFound, :with => :render_404
  rescue_from ActionController::RoutingError, :with => :render_404
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  def render_404
    render :template => "errors/404", :layout => 'application', :status => 404 and return false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :get_templates, :only => [:new, :edit, :create, :update]
  before_filter :get_page, :only => [:edit, :update, :destroy, :show]
  before_filter :require_owner, :only => [:edit, :update, :destroy]

  def index
    @pages = Page.all
  end

  def show
    @body_class = @page.template.class_name unless @page.template.nil?
  end

  def new
    @page = Page.new
  end

  def edit
  end

  def create
    @page = Page.new(params[:page])
    @page.owner = current_user

    if @page.save
      redirect_to @page, notice: 'Page was successfully created.'
    else
      render :new
    end
  end

  def update
    if @page.update_attributes(params[:page])
      redirect_to @page, notice: 'Page was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @page.destroy

    redirect_to pages_url
  end

  private
    def get_templates
      @templates = Template.all
    end

    def get_page
      @page = Page.find(params[:id])
    end

    def require_owner
      unless @page.allows_editor?(current_user)
        redirect_to pages_path, alert: t('errors.bad_editor') and return false
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  include Devise::Controllers::Rememberable

  Devise.omniauth_providers.each do |provider|
    define_method(provider) { default }
  end

  private
  def default
    user = User.find_or_create_by_omniauth_hash(request.env['omniauth.auth'], current_user)
    remember_me(user)
    sign_in_and_redirect(user, event: :authentication)
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/admin/home/index.html.erb
<%= link_to "Home", root_path %>
<h1>Admin Panel</h1>
<p><%= link_to "View templates", admin_templates_path %></p>

app/views/admin/templates/_form.html.erb
<%= form_for([:admin, @template]) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :class_name %><br />
    <%= f.text_field :class_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @template] %> |
<%= link_to 'Back', admin_templates_path %>

app/views/admin/templates/index.html.erb
<h1>Listing templates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Class name</th>
    <th>Description</th>
    <th>Created by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @templates.each do |template| %>
  <tr>
    <td><%= template.name %></td>
    <td><%= template.class_name %></td>
    <td><%= template.description %></td>
    <td><%= template.created_by_id %></td>
    <td><%= link_to 'Show', [:admin, template] %></td>
    <td><%= link_to 'Edit', edit_admin_template_path(template) %></td>
    <td><%= link_to 'Destroy', [:admin, template], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Template', new_admin_template_path %>

app/views/admin/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_templates_path %>

app/views/admin/templates/show.html.erb
<p>
  <b>Name:</b>
  <%= @template.name %>
</p>

<p>
  <b>Class name:</b>
  <%= @template.class_name %>
</p>

<p>
  <b>Description:</b>
  <%= @template.description %>
</p>

<p>
  <b>Created by:</b>
  <%= @template.created_by_id %>
</p>


<%= link_to 'Edit', edit_admin_template_path(@template) %> |
<%= link_to 'Back', admin_templates_path %>

app/views/home/index.html.erb
<h1>Someday this will be a home page</h1>

<ul>
  <li><%= link_to "View pages", pages_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tribute</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag 'modernizr.min' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= @body_class || '' %>">
 <%= render partial: "/shared/header" %>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for @page, :html => { :multipart => true } do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br />
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :main_image %><br />
    <%= f.file_field :main_image %>
    <%= f.hidden_field :main_image_cache %>
  </div>
  <div class="field">
    <%= f.label :template_id %><br />
    <%= f.collection_select :template_id, @templates, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Tagline</th>
    <th>Description</th>
    <th>Main image</th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.name %></td>
    <td><%= page.tagline %></td>
    <td><%= page.description %></td>
    <td><%= page.main_image %></td>
    <td>
      <%= link_to 'Show', page %>
      <% if page.allows_editor?(current_user) %>
        | <%= link_to 'Edit', edit_page_path(page) %>
        | <%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
  </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p>
  <b>Name:</b>
  <%= @page.name %>
</p>

<p>
  <b>Tagline:</b>
  <%= @page.tagline %>
</p>

<p>
  <b>Description:</b>
  <%= @page.description %>
</p>

<p>
  <b>Main image:</b>
  <%= link_to @page.main_image.url, target: '_blank' do %>
    <%= image_tag @page.main_image.thumb %>
  <% end %>
</p>

<p>
  <b>Template:</b>
  <%= @page.template.name %>
</p>


<% if @page.allows_editor?(current_user) %>
  <%= link_to 'Edit', edit_page_path(@page) %> |
<% end %>
<%= link_to 'Back', pages_path %>

app/views/shared/_header.html.erb
<header>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if current_user %>
    <p>Hello, <%= current_user.first_name %></p>
    <p>
      <%= link_to "Sign Out", destroy_user_session_path %>
      <% if current_user.admin? %>
        | <%= link_to "Admin Home", admin_root_path %>
      <% end %>
    </p> 
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path %> | <%= link_to "Sign In", new_user_session_path %>
  <% end %>
</header>

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :class_name %><br />
    <%= f.text_field :class_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/templates/index.html.erb
<h1>Listing templates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Class name</th>
    <th>Description</th>
    <th>Created by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @templates.each do |template| %>
  <tr>
    <td><%= template.name %></td>
    <td><%= template.class_name %></td>
    <td><%= template.description %></td>
    <td><%= template.created_by_id %></td>
    <td><%= link_to 'Show', template %></td>
    <td><%= link_to 'Edit', edit_template_path(template) %></td>
    <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p>
  <b>Name:</b>
  <%= @template.name %>
</p>

<p>
  <b>Class name:</b>
  <%= @template.class_name %>
</p>

<p>
  <b>Description:</b>
  <%= @template.description %>
</p>

<p>
  <b>Created by:</b>
  <%= @template.created_by_id %>
</p>


<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>